management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    bus-env:
      enabled: true
    bus-refresh:
      enabled: true


server:
  port: 8888
spring:
  cloud:
    consul:
      discovery:
        service-name: ConfigServer
      host: 127.0.0.1
      port: 8500
    config:
      server:
        git:
          uri: file:///E:\GradleDemoManyModules\ExampleHelloWorld\configRepo\config-repo

  application:
    name: cs

